interface:
  killall: true
  mobkill: true
all-ignore:
- minecarts
- tamed
- itemframes
- paintings
- boats
disallow:
- itemframes
- paintings

strings:
  commandNonExistant: '&cThat command does not exist.'
  entityNotAllowed: '&cYou are not allowed to use that command on that entity type.'
  help:
  - '&6[KillAllInterface] &7Commands:'
  - '&cUsage: /killallinterface <command>'
  - '&chelp  &7View a list of all KillAllInterface commands.'
  - '&creload  &7Reload the plugin.'
  info:
  - '&6[WGTreeFarmFlag] &7Version %version%'
  - '&6[WGTreeFarmFlag] &7By S_Ryan'
  noPermission: '&cYou do not have permission for that command.'
  reloaded: '&6[KillAllInterface] &7Successfully reloaded.'